apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: petclinic
  name: petclinic-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      label: app
  template:
    metadata:
      labels:
        label: app
    spec:
      containers:
        - image: 'adrf968/petclinic:20'
          imagePullPolicy: IfNotPresent
          name: petclinic
          ports:
            - containerPort: 80
