apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      label: app
  template:
    metadata:
      labels:
        label: app
    spec:
      containers:
      - name: petclinic
        image: adrf968/petclinic:4
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
